DROP DATABASE IF EXISTS PROYECTO;

CREATE DATABASE PROYECTO;
USE PROYECTO;

CREATE TABLE USUARIOS(
	ID INT(4) PRIMARY KEY AUTO_INCREMENT,
	NOMBRECORTO VARCHAR(25) NOT NULL,
	PASSWORD VARCHAR(25) NOT NULL,
	ROLE CHAR(7),
	CONSTRAINT CK_ROLE CHECK (ROLE IN ('Admin', 'Cliente'))
);

INSERT INTO USUARIOS VALUES (NULL,'admin','Root1234','Admin'); 
INSERT INTO USUARIOS VALUES (NULL,'pepe','pepe','Cliente');